"""create weaving_daily_productions table

Revision ID: 06d4d2070abd
Revises: 217b71ec4b06
Create Date: 2026-01-17 12:29:59.850993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06d4d2070abd'
down_revision: Union[str, Sequence[str], None] = '217b71ec4b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaving_daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_meters', sa.Float(), nullable=True),
    sa.Column('total_kg', sa.Float(), nullable=True),
    sa.Column('active_machine_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'product_id', name='uix_date_product')
    )
    op.create_index(op.f('ix_weaving_daily_productions_date'), 'weaving_daily_productions', ['date'], unique=False)
    op.create_index(op.f('ix_weaving_daily_productions_id'), 'weaving_daily_productions', ['id'], unique=False)
    op.add_column('machines', sa.Column('area', sa.Enum('SECTION_A', 'SECTION_B', 'SECTION_C', name='machinearea'), nullable=True))
    op.alter_column('machines', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('STOPPED', 'RUNNING', 'MAINTENANCE', 'SPINNING', name='machinestatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_machines_area'), 'machines', ['area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_area'), table_name='machines')
    op.alter_column('machines', 'status',
               existing_type=sa.Enum('STOPPED', 'RUNNING', 'MAINTENANCE', 'SPINNING', name='machinestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('machines', 'area')
    op.drop_index(op.f('ix_weaving_daily_productions_id'), table_name='weaving_daily_productions')
    op.drop_index(op.f('ix_weaving_daily_productions_date'), table_name='weaving_daily_productions')
    op.drop_table('weaving_daily_productions')
    # ### end Alembic commands ###
