"""Them bang employee_groups

Revision ID: 0a7d7e9aad74
Revises: 31772213f699
Create Date: 2026-03-04 13:55:30.001640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7d7e9aad74'
down_revision: Union[str, Sequence[str], None] = '31772213f699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_employee_groups_group_id'), 'employee_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_employee_groups_group_name'), 'employee_groups', ['group_name'], unique=True)
    op.add_column('employees', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employee_groups', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'group_id')
    op.drop_index(op.f('ix_employee_groups_group_name'), table_name='employee_groups')
    op.drop_index(op.f('ix_employee_groups_group_id'), table_name='employee_groups')
    op.drop_table('employee_groups')
    # ### end Alembic commands ###
