"""delete material_name  column for materials table

Revision ID: 0f9f4b4b476f
Revises: 68ff99400457
Create Date: 2026-01-25 07:14:58.558350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f9f4b4b476f'
down_revision: Union[str, Sequence[str], None] = '68ff99400457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'area',
               existing_type=mysql.ENUM('Khu A', 'Khu B', 'Khu C'),
               type_=sa.Enum('SECTION_A', 'SECTION_B', 'SECTION_C', name='machinearea'),
               existing_nullable=True)
    op.drop_column('materials', 'material_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('material_name', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('machines', 'area',
               existing_type=sa.Enum('SECTION_A', 'SECTION_B', 'SECTION_C', name='machinearea'),
               type_=mysql.ENUM('Khu A', 'Khu B', 'Khu C'),
               existing_nullable=True)
    # ### end Alembic commands ###
