"""remove supplierId for baskets and machines table, update suppliers table vs2

Revision ID: 14425932bc73
Revises: ef5a4566edd4
Create Date: 2026-01-13 02:05:08.827383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14425932bc73'
down_revision: Union[str, Sequence[str], None] = 'ef5a4566edd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- [FIX START] TẠO BÙ CÁC CỘT BỊ THIẾU ---
    # Do migration trước bị lỗi nên các cột này chưa được tạo.
    # Ta tạo chúng ở đây trước khi thực hiện Alter.
    
    try:
        # Tạo cột origin_type (lưu tạm là String để tí nữa Alter sang Enum sau)
        op.add_column('suppliers', sa.Column('origin_type', sa.String(length=20), nullable=True))
    except Exception: pass

    try:
        op.add_column('suppliers', sa.Column('country_code', sa.String(length=100), nullable=True))
    except Exception: pass

    try:
        op.add_column('suppliers', sa.Column('currency_default', sa.String(length=3), nullable=True))
    except Exception: pass
    
    # Tạo thêm các cột khác cho chắc chắn (dù lệnh alter bên dưới không đụng tới)
    try:
        op.add_column('suppliers', sa.Column('short_name', sa.String(length=50), nullable=True))
    except Exception: pass
    try:
        op.add_column('suppliers', sa.Column('contact_person', sa.String(length=100), nullable=True))
    except Exception: pass
    try:
        op.add_column('suppliers', sa.Column('tax_code', sa.String(length=50), nullable=True))
    except Exception: pass
    try:
        op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    except Exception: pass
    try:
        op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=True))
    except Exception: pass
    # --- [FIX END] ---


    # Các lệnh Alter gốc của file (Giữ nguyên)
    # Bây giờ cột đã có, lệnh alter sẽ chạy mượt mà
    try:
        op.alter_column('suppliers', 'origin_type',
                   existing_type=mysql.VARCHAR(length=20),
                   type_=sa.Enum('DOMESTIC', 'IMPORT', name='supplierorigintype'),
                   existing_nullable=True)
    except Exception: pass

    try:
        op.alter_column('suppliers', 'country_code',
                   existing_type=mysql.VARCHAR(length=3),
                   type_=sa.String(length=100),
                   existing_nullable=True)
    except Exception: pass

    try:
        op.alter_column('suppliers', 'currency_default',
                   existing_type=mysql.VARCHAR(length=3),
                   type_=sa.Enum('VND', 'USD', name='currencytype'),
                   existing_nullable=True)
    except Exception: pass

    try:
        op.alter_column('suppliers', 'email',
                   existing_type=mysql.VARCHAR(length=100),
                   nullable=False)
    except Exception: pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'currency_default',
               existing_type=sa.Enum('VND', 'USD', name='currencytype'),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('suppliers', 'country_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('suppliers', 'origin_type',
               existing_type=sa.Enum('DOMESTIC', 'IMPORT', name='supplierorigintype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###