"""create table weaving daily production

Revision ID: 144da03464af
Revises: 34ef9b88d8a5
Create Date: 2026-01-14 03:35:05.340863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144da03464af'
down_revision: Union[str, Sequence[str], None] = '34ef9b88d8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaving_daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_meters', sa.Float(), nullable=True),
    sa.Column('total_kg', sa.Float(), nullable=True),
    sa.Column('active_machine_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'product_id', name='uix_date_product')
    )
    op.create_index(op.f('ix_weaving_daily_productions_date'), 'weaving_daily_productions', ['date'], unique=False)
    op.create_index(op.f('ix_weaving_daily_productions_id'), 'weaving_daily_productions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaving_daily_productions_id'), table_name='weaving_daily_productions')
    op.drop_index(op.f('ix_weaving_daily_productions_date'), table_name='weaving_daily_productions')
    op.drop_table('weaving_daily_productions')
    # ### end Alembic commands ###
