"""create BOMHeader and BOMDetail tables vs2

Revision ID: 1534c2487c44
Revises: 3633c54a2f97
Create Date: 2026-01-19 05:25:40.466831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1534c2487c44'
down_revision: Union[str, Sequence[str], None] = '3633c54a2f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_headers',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bom_code', sa.String(length=50), nullable=False),
    sa.Column('bom_name', sa.String(length=150), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('base_quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('bom_id')
    )
    op.create_index(op.f('ix_bom_headers_bom_code'), 'bom_headers', ['bom_code'], unique=True)
    op.create_index(op.f('ix_bom_headers_bom_id'), 'bom_headers', ['bom_id'], unique=False)
    op.create_table('bom_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('WARP', 'WEFT', 'BINDER', 'DYE', name='bomcomponenttype'), nullable=False),
    sa.Column('number_of_ends', sa.Integer(), nullable=True, comment='Tổng số sợi dọc'),
    sa.Column('quantity_standard', sa.Float(), nullable=False, comment='Số lượng chuẩn (g/m)'),
    sa.Column('wastage_rate', sa.Float(), nullable=True, comment='Tỷ lệ hao hụt (%)'),
    sa.Column('quantity_gross', sa.Float(), nullable=False, comment='Tổng lượng cần xuất kho bao gồm hao hụt'),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_headers.bom_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_bom_details_detail_id'), 'bom_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_details_detail_id'), table_name='bom_details')
    op.drop_table('bom_details')
    op.drop_index(op.f('ix_bom_headers_bom_id'), table_name='bom_headers')
    op.drop_index(op.f('ix_bom_headers_bom_code'), table_name='bom_headers')
    op.drop_table('bom_headers')
    # ### end Alembic commands ###
