"""remove code column for standards table

Revision ID: 20ef430d0067
Revises: bb645ccedc2d
Create Date: 2026-01-06 03:35:20.274819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20ef430d0067'
down_revision: Union[str, Sequence[str], None] = 'bb645ccedc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_column('standards', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('code', mysql.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    # ### end Alembic commands ###
