"""Them cot so cuon tren PO

Revision ID: 28f1b0ecc033
Revises: 5ef69ce04504
Create Date: 2026-02-02 03:47:29.470891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f1b0ecc033'
down_revision: Union[str, Sequence[str], None] = '5ef69ce04504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_details', sa.Column('quantity_rolls', sa.Integer(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('received_rolls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_details', 'received_rolls')
    op.drop_column('purchase_order_details', 'quantity_rolls')
    # ### end Alembic commands ###
