"""Them truong pallet_number cho bang material_inventory

Revision ID: 29368da59e91
Revises: 37631d405260
Create Date: 2026-03-10 05:51:48.083912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29368da59e91'
down_revision: Union[str, Sequence[str], None] = '37631d405260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_inventories', sa.Column('number_of_pallets', sa.Integer(), nullable=True, comment='Số lượng Pallet/Kiện hàng'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_inventories', 'number_of_pallets')
    # ### end Alembic commands ###
