"""update bom table vs2 

Revision ID: 2df4d5837a01
Revises: b789be87d93d
Create Date: 2026-01-26 04:53:49.224898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2df4d5837a01'
down_revision: Union[str, Sequence[str], None] = 'b789be87d93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom_details', 'yarn_type_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='Mã sợi/Màu (Cột D)',
               existing_comment='Mã sợi/Màu (Cột D - VD: 03300-PES-WEISS)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom_details', 'yarn_type_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='Mã sợi/Màu (Cột D - VD: 03300-PES-WEISS)',
               existing_comment='Mã sợi/Màu (Cột D)',
               existing_nullable=True)
    # ### end Alembic commands ###
