"""Update user role to Enum worker vs3

Revision ID: 316b6776e0a4
Revises: 5caa8698e76e
Create Date: 2026-02-02 09:34:26.565686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316b6776e0a4'
down_revision: Union[str, Sequence[str], None] = '5caa8698e76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
