"""Them bang machine_product_histories

Revision ID: 31772213f699
Revises: aad20080ff10
Create Date: 2026-03-01 15:11:36.055767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31772213f699'
down_revision: Union[str, Sequence[str], None] = 'aad20080ff10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_product_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_product_histories_id'), 'machine_product_histories', ['id'], unique=False)
    op.drop_constraint(op.f('weaving_productions_ibfk_2'), 'weaving_productions', type_='foreignkey')
    op.create_foreign_key(None, 'weaving_productions', 'weaving_machines', ['machine_id'], ['machine_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weaving_productions', type_='foreignkey')
    op.create_foreign_key(op.f('weaving_productions_ibfk_2'), 'weaving_productions', 'machines', ['machine_id'], ['machine_id'])
    op.drop_index(op.f('ix_machine_product_histories_id'), table_name='machine_product_histories')
    op.drop_table('machine_product_histories')
    # ### end Alembic commands ###
