"""add payment_term column for suppliers table 

Revision ID: 3220018f8dd6
Revises: 0872ffc987cf
Create Date: 2026-01-19 03:20:53.619667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3220018f8dd6'
down_revision: Union[str, Sequence[str], None] = '0872ffc987cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('payment_term', sa.Enum('TT', 'LC', 'NET_30', 'NET_45', 'NET_60', 'COD', 'IMMEDIATE', name='paymenttermtype'), nullable=True, comment='Điều khoản thanh toán mặc định (T/T, L/C, Net 30...)'))
    op.alter_column('suppliers', 'lead_time_days',
               existing_type=mysql.INTEGER(),
               comment='Thời gian giao hàng trung bình (ngày)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'lead_time_days',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Thời gian giao hàng trung bình (ngày)',
               existing_nullable=True)
    op.drop_column('suppliers', 'payment_term')
    # ### end Alembic commands ###
