"""remove supplierId for baskets and machines table, update suppliers table vs4

Revision ID: 34ef9b88d8a5
Revises: 6694a4ff24fc
Create Date: 2026-01-14 01:56:08.420325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34ef9b88d8a5'
down_revision: Union[str, Sequence[str], None] = '6694a4ff24fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('area', sa.Enum('SECTION_A', 'SECTION_B', 'SECTION_C', name='machinearea'), nullable=True))
    op.alter_column('machines', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('STOPPED', 'RUNNING', 'MAINTENANCE', 'SPINNING', name='machinestatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_machines_area'), 'machines', ['area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_area'), table_name='machines')
    op.alter_column('machines', 'status',
               existing_type=sa.Enum('STOPPED', 'RUNNING', 'MAINTENANCE', 'SPINNING', name='machinestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('machines', 'area')
    # ### end Alembic commands ###
