"""Them cot material_name vào bang materials

Revision ID: 356198dce4fb
Revises: 316b6776e0a4
Create Date: 2026-02-05 03:41:04.826694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356198dce4fb'
down_revision: Union[str, Sequence[str], None] = '316b6776e0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('material_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_materials_material_name'), 'materials', ['material_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_material_name'), table_name='materials')
    op.drop_column('materials', 'material_name')
    # ### end Alembic commands ###
