"""create warehouses, material_receipts and material_receipt_details table

Revision ID: 367bcda1e2c5
Revises: 91bae4191a6a
Create Date: 2026-01-22 02:27:38.308864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367bcda1e2c5'
down_revision: Union[str, Sequence[str], None] = '91bae4191a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_name'), 'warehouses', ['warehouse_name'], unique=True)
    op.create_table('material_receipts',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('po_header_id', sa.Integer(), nullable=True),
    sa.Column('declaration_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('container_no', sa.String(length=50), nullable=True, comment='Số Container'),
    sa.Column('seal_no', sa.String(length=50), nullable=True, comment='Số Seal (Chì)'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['po_header_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_index(op.f('ix_material_receipts_receipt_id'), 'material_receipts', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_receipt_number'), 'material_receipts', ['receipt_number'], unique=True)
    op.create_table('material_receipt_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('po_quantity_kg', sa.Float(), nullable=True, comment='SL Kg trên chứng từ'),
    sa.Column('po_quantity_cones', sa.Integer(), nullable=True, comment='SL Cuộn trên chứng từ'),
    sa.Column('received_quantity_kg', sa.Float(), nullable=False, comment='SL Kg thực nhập'),
    sa.Column('received_quantity_cones', sa.Integer(), nullable=True, comment='SL Cuộn thực nhập'),
    sa.Column('number_of_pallets', sa.Integer(), nullable=True, comment='Tổng số Pallet/Kiện hàng'),
    sa.Column('supplier_batch_no', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['material_receipts.receipt_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_material_receipt_details_detail_id'), 'material_receipt_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_receipt_details_detail_id'), table_name='material_receipt_details')
    op.drop_table('material_receipt_details')
    op.drop_index(op.f('ix_material_receipts_receipt_number'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_receipt_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_warehouses_warehouse_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
