"""Cap nhat lai bang weaving_production

Revision ID: 369dfb290dd0
Revises: 3b7d02793c5a
Create Date: 2026-03-13 05:17:52.688417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369dfb290dd0'
down_revision: Union[str, Sequence[str], None] = '3b7d02793c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaving_productions', sa.Column('weaving_ticket_id', sa.Integer(), nullable=True))
    op.add_column('weaving_productions', sa.Column('run_waste_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_weaving_productions_weaving_ticket_id'), 'weaving_productions', ['weaving_ticket_id'], unique=False)
    op.create_foreign_key(None, 'weaving_productions', 'weaving_basket_tickets', ['weaving_ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weaving_productions', type_='foreignkey')
    op.drop_index(op.f('ix_weaving_productions_weaving_ticket_id'), table_name='weaving_productions')
    op.drop_column('weaving_productions', 'run_waste_reason')
    op.drop_column('weaving_productions', 'weaving_ticket_id')
    # ### end Alembic commands ###
