"""Cap nhat material_batch, material_receip, material_inventory

Revision ID: 37631d405260
Revises: 98329fc670a5
Create Date: 2026-03-09 03:34:55.292626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37631d405260'
down_revision: Union[str, Sequence[str], None] = '98329fc670a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Tạo các bảng mới
    op.create_table('material_batches',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('receipt_detail_id', sa.Integer(), nullable=True),
    sa.Column('supplier_batch_no', sa.String(length=100), nullable=True, comment='Mã lô của Nhà cung cấp'),
    sa.Column('origin_country', sa.String(length=50), nullable=True, comment='Quốc gia xuất xứ'),
    sa.Column('manufacturing_date', sa.Date(), nullable=True, comment='Ngày sản xuất'),
    sa.Column('expiration_date', sa.Date(), nullable=True, comment='Ngày hết hạn (Nếu có)'),
    sa.Column('initial_quantity_kg', sa.Float(), nullable=True, comment='Tổng Kg ban đầu của lô'),
    sa.Column('initial_quantity_cones', sa.Integer(), nullable=True, comment='Tổng số cuộn ban đầu của lô'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Available, Quarantine, Blocked, Depleted'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['receipt_detail_id'], ['material_receipt_details.detail_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_material_batches_batch_code'), 'material_batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_material_batches_batch_id'), 'material_batches', ['batch_id'], unique=False)
    
    op.create_table('material_inventories',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True, comment='Vị trí kho chi tiết'),
    sa.Column('quantity_kg', sa.Float(), nullable=False, comment='Số lượng Kg khả dụng'),
    sa.Column('quantity_cones', sa.Integer(), nullable=False, comment='Số lượng cuộn khả dụng'),
    sa.Column('reserved_quantity_kg', sa.Float(), nullable=True, comment='Số lượng Kg đã được giữ chỗ'),
    sa.Column('reserved_quantity_cones', sa.Integer(), nullable=True, comment='Số lượng cuộn đã được giữ chỗ'),
    sa.Column('last_counted_date', sa.DateTime(), nullable=True, comment='Ngày kiểm kê gần nhất'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['material_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('warehouse_id', 'material_id', 'batch_id', 'location', name='_wh_mat_batch_loc_uc')
    )
    op.create_index(op.f('ix_material_inventories_inventory_id'), 'material_inventories', ['inventory_id'], unique=False)
    
    # 2. XÓA CÁC KHÓA NGOẠI TRỎ TỚI CÁC BẢNG CŨ (RẤT QUAN TRỌNG - PHẢI LÀM TRƯỚC KHI DROP TABLE)
    op.drop_constraint('iqc_results_ibfk_1', 'iqc_results', type_='foreignkey')
    op.drop_constraint('material_export_details_ibfk_2', 'material_export_details', type_='foreignkey')
    op.drop_constraint('weaving_ticket_yarns_ibfk_1', 'weaving_ticket_yarns', type_='foreignkey')

    # 3. Trỏ lại các Khóa ngoại vào bảng material_batches mới
    op.create_foreign_key(None, 'iqc_results', 'material_batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key(None, 'material_export_details', 'material_batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key(None, 'weaving_ticket_yarns', 'material_batches', ['batch_id'], ['batch_id'])

    # 4. Xóa bảng inventory_stocks (Không dùng drop_index thủ công để tránh lỗi MySQL)
    op.drop_table('inventory_stocks')
    
    # 5. Xóa bảng batches (Không dùng drop_index thủ công)
    op.drop_table('batches')
    
    # 6. Cập nhật bảng material_receipts
    op.add_column('material_receipts', sa.Column('status', sa.String(length=20), nullable=True, comment='Draft, Completed, Cancelled'))
    op.drop_constraint('material_receipts_ibfk_1', 'material_receipts', type_='foreignkey')
    op.drop_column('material_receipts', 'declaration_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Trả lại khóa ngoại bảng phụ (Tháo từ material_batches)
    op.drop_constraint(None, 'weaving_ticket_yarns', type_='foreignkey')
    op.drop_constraint(None, 'material_export_details', type_='foreignkey')
    op.drop_constraint(None, 'iqc_results', type_='foreignkey')
    
    # 2. Khôi phục cột cũ trên material_receipts
    op.add_column('material_receipts', sa.Column('declaration_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('material_receipts_ibfk_1', 'material_receipts', 'import_declarations', ['declaration_id'], ['id'])
    op.drop_column('material_receipts', 'status')
    
    # 3. Tạo lại bảng batches cũ
    op.create_table('batches',
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('internal_batch_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('supplier_batch_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacture_date', sa.DATE(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('origin_country', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=10), nullable=True, comment='Vị trí kho/Bin code'),
    sa.Column('receipt_detail_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_status', mysql.ENUM('PENDING', 'PASS', 'FAIL', 'EXPIRED'), nullable=True),
    sa.Column('qc_note', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name='batches_ibfk_1'),
    sa.ForeignKeyConstraint(['receipt_detail_id'], ['material_receipt_details.detail_id'], name='batches_ibfk_2'),
    sa.PrimaryKeyConstraint('batch_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_batches_supplier_batch_no', 'batches', ['supplier_batch_no'], unique=False)
    op.create_index('ix_batches_internal_batch_code', 'batches', ['internal_batch_code'], unique=True)
    op.create_index('ix_batches_batch_id', 'batches', ['batch_id'], unique=False)
    
    # 4. Trỏ lại Khóa ngoại vào bảng batches
    op.create_foreign_key('weaving_ticket_yarns_ibfk_1', 'weaving_ticket_yarns', 'batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key('material_export_details_ibfk_2', 'material_export_details', 'batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key('iqc_results_ibfk_1', 'iqc_results', 'batches', ['batch_id'], ['batch_id'])

    # 5. Tạo lại bảng inventory_stocks
    op.create_table('inventory_stocks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_on_hand', mysql.FLOAT(), nullable=True),
    sa.Column('quantity_reserved', mysql.FLOAT(), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name='inventory_stocks_ibfk_1'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name='inventory_stocks_ibfk_2'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], name='inventory_stocks_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uix_stock_loc_batch', 'inventory_stocks', ['material_id', 'warehouse_id', 'batch_id'], unique=True)
    op.create_index('ix_inventory_stocks_id', 'inventory_stocks', ['id'], unique=False)
    
    # 6. Xóa các bảng mới
    op.drop_index(op.f('ix_material_inventories_inventory_id'), table_name='material_inventories')
    op.drop_table('material_inventories')
    op.drop_index(op.f('ix_material_batches_batch_id'), table_name='material_batches')
    op.drop_index(op.f('ix_material_batches_batch_code'), table_name='material_batches')
    op.drop_table('material_batches')
    # ### end Alembic commands ###