"""update bom table vs3 

Revision ID: 395126741d8b
Revises: 2df4d5837a01
Create Date: 2026-01-26 08:45:23.859401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '395126741d8b'
down_revision: Union[str, Sequence[str], None] = '2df4d5837a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom_details', 'yarn_dtex',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Độ mảnh sợi dtex (Cột C)',
               existing_nullable=True)
    op.alter_column('bom_details', 'twisted',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Hệ số xoắn (Cột E)',
               existing_nullable=True)
    op.alter_column('bom_details', 'crossweave_rate',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Độ dôi sợi/Crimp % (Cột F)',
               existing_nullable=True)
    op.alter_column('bom_details', 'weight_per_yarn_gm',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Trọng lượng lý thuyết g/m (Cột G)',
               existing_nullable=True)
    op.alter_column('bom_details', 'actual_length_cm',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Chiều dài sợi thực tế đo được (Cột H)',
               existing_nullable=True)
    op.alter_column('bom_details', 'actual_weight_cal',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Trọng lượng thực tế tính toán (Cột I)',
               existing_nullable=True)
    op.alter_column('bom_details', 'weight_percentage',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Tỷ lệ % khối lượng (Cột J)',
               existing_nullable=True)
    op.alter_column('bom_details', 'bom_gm',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=20, scale=10),
               existing_comment='Định mức chốt cuối cùng (Cột K)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'width_behind_loom',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Width behind loom (mm/cm)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'target_weight_gm',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Trọng lượng mục tiêu (80.1 g/m)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'total_scrap_rate',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Tỷ lệ hao hụt tổng (F18)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'total_shrinkage_rate',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Tỷ lệ co rút tổng (F19)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom_headers', 'total_shrinkage_rate',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='Tỷ lệ co rút tổng (F19)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'total_scrap_rate',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='Tỷ lệ hao hụt tổng (F18)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'target_weight_gm',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='Trọng lượng mục tiêu (80.1 g/m)',
               existing_nullable=True)
    op.alter_column('bom_headers', 'width_behind_loom',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='Width behind loom (mm/cm)',
               existing_nullable=True)
    op.alter_column('bom_details', 'bom_gm',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Định mức chốt cuối cùng (Cột K)',
               existing_nullable=True)
    op.alter_column('bom_details', 'weight_percentage',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Tỷ lệ % khối lượng (Cột J)',
               existing_nullable=True)
    op.alter_column('bom_details', 'actual_weight_cal',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Trọng lượng thực tế tính toán (Cột I)',
               existing_nullable=True)
    op.alter_column('bom_details', 'actual_length_cm',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Chiều dài sợi thực tế đo được (Cột H)',
               existing_nullable=True)
    op.alter_column('bom_details', 'weight_per_yarn_gm',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Trọng lượng lý thuyết g/m (Cột G)',
               existing_nullable=True)
    op.alter_column('bom_details', 'crossweave_rate',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Độ dôi sợi/Crimp % (Cột F)',
               existing_nullable=True)
    op.alter_column('bom_details', 'twisted',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Hệ số xoắn (Cột E)',
               existing_nullable=True)
    op.alter_column('bom_details', 'yarn_dtex',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               type_=mysql.FLOAT(),
               existing_comment='Độ mảnh sợi dtex (Cột C)',
               existing_nullable=True)
    # ### end Alembic commands ###
