"""Cap nhat lai bang machine_logs

Revision ID: 3b7d02793c5a
Revises: 936cc04dfea3
Create Date: 2026-03-13 01:26:15.362515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7d02793c5a'
down_revision: Union[str, Sequence[str], None] = '936cc04dfea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_logs', sa.Column('line_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_logs', 'line_number')
    # ### end Alembic commands ###
