"""Them bang cot overtime_hours cho bang work_schedules 

Revision ID: 3edcdd512f23
Revises: 0a7d7e9aad74
Create Date: 2026-03-04 15:39:18.723844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edcdd512f23'
down_revision: Union[str, Sequence[str], None] = '0a7d7e9aad74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_schedules', sa.Column('overtime_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_schedules', 'overtime_hours')
    # ### end Alembic commands ###
