"""create table material_export and material_export_detail table vs2

Revision ID: 4457710f96c5
Revises: 57e7d3705be4
Create Date: 2026-01-28 09:13:55.168166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4457710f96c5'
down_revision: Union[str, Sequence[str], None] = '57e7d3705be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_export_details', sa.Column('machine_line', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_export_details', 'machine_line')
    # ### end Alembic commands ###
