"""create table material_export and material_export_detail table

Revision ID: 57e7d3705be4
Revises: f577c0034c83
Create Date: 2026-01-28 07:47:20.902713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e7d3705be4'
down_revision: Union[str, Sequence[str], None] = 'f577c0034c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_code', sa.String(length=50), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_exports_export_code'), 'material_exports', ['export_code'], unique=True)
    op.create_index(op.f('ix_material_exports_id'), 'material_exports', ['id'], unique=False)
    op.create_table('material_export_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('export_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['export_id'], ['material_exports.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.standard_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_material_export_details_detail_id'), 'material_export_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_export_details_detail_id'), table_name='material_export_details')
    op.drop_table('material_export_details')
    op.drop_index(op.f('ix_material_exports_id'), table_name='material_exports')
    op.drop_index(op.f('ix_material_exports_export_code'), table_name='material_exports')
    op.drop_table('material_exports')
    # ### end Alembic commands ###
