"""Update user role to Enum

Revision ID: 5d8b70add31e
Revises: f6ac2f576aa8
Create Date: 2026-02-02 05:08:25.890861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d8b70add31e'
down_revision: Union[str, Sequence[str], None] = 'f6ac2f576aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
