"""Cap nhat PO

Revision ID: 5edec9e2bb78
Revises: efcd146d2751
Create Date: 2026-03-06 18:15:33.592160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5edec9e2bb78'
down_revision: Union[str, Sequence[str], None] = 'efcd146d2751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    op.drop_table('purchase_orders')
    op.drop_constraint(op.f('material_receipts_ibfk_2'), 'material_receipts', type_='foreignkey')
    op.create_foreign_key(None, 'material_receipts', 'purchase_order_headers', ['po_header_id'], ['po_id'])
    op.add_column('purchase_order_details', sa.Column('ocean_freight', sa.Float(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('confirm_delivery', sa.String(length=50), nullable=True))
    op.add_column('purchase_order_details', sa.Column('goods_readiness', sa.String(length=50), nullable=True))
    op.add_column('purchase_order_details', sa.Column('shipping_line', sa.String(length=100), nullable=True))
    op.add_column('purchase_order_details', sa.Column('forwarder', sa.String(length=100), nullable=True))
    op.add_column('purchase_order_details', sa.Column('etd', sa.Date(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('eta', sa.Date(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('atd', sa.Date(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('booking_date', sa.Date(), nullable=True))
    op.drop_constraint(op.f('purchase_order_details_ibfk_2'), 'purchase_order_details', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_order_details', 'purchase_order_headers', ['po_id'], ['po_id'])
    op.drop_column('purchase_order_details', 'exchange_rate')
    op.execute('SET FOREIGN_KEY_CHECKS=1;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_details', sa.Column('exchange_rate', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'purchase_order_details', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_order_details_ibfk_2'), 'purchase_order_details', 'purchase_orders', ['po_id'], ['po_id'])
    op.drop_column('purchase_order_details', 'booking_date')
    op.drop_column('purchase_order_details', 'atd')
    op.drop_column('purchase_order_details', 'eta')
    op.drop_column('purchase_order_details', 'etd')
    op.drop_column('purchase_order_details', 'forwarder')
    op.drop_column('purchase_order_details', 'shipping_line')
    op.drop_column('purchase_order_details', 'goods_readiness')
    op.drop_column('purchase_order_details', 'confirm_delivery')
    op.drop_column('purchase_order_details', 'ocean_freight')
    op.drop_constraint(None, 'material_receipts', type_='foreignkey')
    op.create_foreign_key(op.f('material_receipts_ibfk_2'), 'material_receipts', 'purchase_orders', ['po_header_id'], ['po_id'])
    op.create_table('purchase_orders',
    sa.Column('po_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('expected_arrival_date', sa.DATE(), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('incoterm_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.incoterm_id'], name=op.f('purchase_orders_ibfk_2')),
    sa.ForeignKeyConstraint(['status_id'], ['po_statuses.status_id'], name=op.f('purchase_orders_ibfk_3')),
    sa.ForeignKeyConstraint(['vendor_id'], ['suppliers.supplier_id'], name=op.f('purchase_orders_ibfk_1')),
    sa.PrimaryKeyConstraint('po_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
