"""Them bang weaving productions

Revision ID: 5ef69ce04504
Revises: d0aa037a7e4f
Create Date: 2026-02-01 15:16:10.692304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef69ce04504'
down_revision: Union[str, Sequence[str], None] = 'd0aa037a7e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaving_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('run_waste', sa.Float(), nullable=False),
    sa.Column('setup_waste', sa.Float(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_productions_id'), 'weaving_productions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaving_productions_id'), table_name='weaving_productions')
    op.drop_table('weaving_productions')
    # ### end Alembic commands ###
