"""remove supplierId for baskets and machines table, update suppliers table vs3

Revision ID: 6694a4ff24fc
Revises: 14425932bc73
Create Date: 2026-01-13 06:30:34.298108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6694a4ff24fc'
down_revision: Union[str, Sequence[str], None] = '14425932bc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
