"""update_material_model_fields

Revision ID: 673cfc20dda7
Revises: a2ebfb7cfa57
Create Date: 2026-02-23 04:51:50.712424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '673cfc20dda7'
down_revision: Union[str, Sequence[str], None] = 'a2ebfb7cfa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'color',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_materials_color_type'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_type'), table_name='materials')
    op.drop_index(op.f('ix_materials_type_code'), table_name='materials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_materials_type_code'), 'materials', ['material_type', 'material_code'], unique=False)
    op.create_index(op.f('ix_materials_material_type'), 'materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_materials_color_type'), 'materials', ['color', 'material_type'], unique=False)
    op.alter_column('materials', 'color',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
