"""Them truong line cho loom

Revision ID: 684b1028d9f6
Revises: 29368da59e91
Create Date: 2026-03-10 08:52:42.745380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684b1028d9f6'
down_revision: Union[str, Sequence[str], None] = '29368da59e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_product_histories', sa.Column('line_number', sa.Integer(), nullable=False, comment='Số thứ tự Line (1, 2, 3...)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_product_histories', 'line_number')
    # ### end Alembic commands ###
