"""create new material table

Revision ID: 685d66a0b0f4
Revises: 52a5ee030885
Create Date: 2026-01-18 11:18:49.084546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '685d66a0b0f4'
down_revision: Union[str, Sequence[str], None] = '52a5ee030885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_issue_slip_details_issue_detail_id'), table_name='material_issue_slip_details')
    op.drop_table('material_issue_slip_details')
    op.drop_index(op.f('ix_material_issue_slips_issue_slip_id'), table_name='material_issue_slips')
    op.drop_table('material_issue_slips')
    op.drop_index(op.f('ix_machine_logs_id'), table_name='machine_logs')
    op.drop_table('machine_logs')
    op.add_column('materials', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('materials', sa.Column('material_code', sa.String(length=50), nullable=False))
    op.add_column('materials', sa.Column('material_type', sa.String(length=50), nullable=True))
    op.add_column('materials', sa.Column('spec_denier', sa.String(length=50), nullable=True))
    op.add_column('materials', sa.Column('spec_filament', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('hs_code', sa.String(length=20), nullable=True))
    op.add_column('materials', sa.Column('min_stock_level', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('uom_base_id', sa.Integer(), nullable=False))
    op.add_column('materials', sa.Column('uom_production_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.drop_constraint(op.f('materials_ibfk_1'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_ibfk_2'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'units', ['uom_base_id'], ['unit_id'])
    op.create_foreign_key(None, 'materials', 'units', ['uom_production_id'], ['unit_id'])
    op.drop_column('materials', 'note')
    op.drop_column('materials', 'imported_by')
    op.drop_column('materials', 'material_id')
    op.drop_column('materials', 'import_date')
    op.drop_column('materials', 'lot_code')
    op.drop_column('materials', 'unit_id')
    op.drop_column('materials', 'quantity')
    op.drop_column('suppliers', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('materials', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('lot_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('materials', sa.Column('import_date', sa.DATE(), nullable=False))
    op.add_column('materials', sa.Column('material_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('materials', sa.Column('imported_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('note', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_ibfk_2'), 'materials', 'units', ['unit_id'], ['unit_id'])
    op.create_foreign_key(op.f('materials_ibfk_1'), 'materials', 'employees', ['imported_by'], ['employee_id'])
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.drop_column('materials', 'uom_production_id')
    op.drop_column('materials', 'uom_base_id')
    op.drop_column('materials', 'min_stock_level')
    op.drop_column('materials', 'hs_code')
    op.drop_column('materials', 'spec_filament')
    op.drop_column('materials', 'spec_denier')
    op.drop_column('materials', 'material_type')
    op.drop_column('materials', 'material_code')
    op.drop_column('materials', 'id')
    op.create_table('machine_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], name=op.f('machine_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_machine_logs_id'), 'machine_logs', ['id'], unique=False)
    op.create_table('material_issue_slips',
    sa.Column('issue_slip_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('note', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('issue_slip_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_material_issue_slips_issue_slip_id'), 'material_issue_slips', ['issue_slip_id'], unique=False)
    op.create_table('material_issue_slip_details',
    sa.Column('issue_detail_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_slip_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('material_issue_slip_details_ibfk_1')),
    sa.ForeignKeyConstraint(['issue_slip_id'], ['material_issue_slips.issue_slip_id'], name=op.f('material_issue_slip_details_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('material_issue_slip_details_ibfk_3')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], name=op.f('material_issue_slip_details_ibfk_4')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name=op.f('material_issue_slip_details_ibfk_5')),
    sa.PrimaryKeyConstraint('issue_detail_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_material_issue_slip_details_issue_detail_id'), 'material_issue_slip_details', ['issue_detail_id'], unique=False)
    # ### end Alembic commands ###
