"""add column location for material_receipts table

Revision ID: 68d207d139a9
Revises: 6e8a4b6afbc1
Create Date: 2026-01-27 06:18:13.416577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d207d139a9'
down_revision: Union[str, Sequence[str], None] = '6e8a4b6afbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_receipt_details', sa.Column('location', sa.String(length=20), nullable=True, comment='Vị trí kho chi tiết (Bin Code)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_receipt_details', 'location')
    # ### end Alembic commands ###
