"""update new bom

Revision ID: 68ff99400457
Revises: f6a6f67f9603
Create Date: 2026-01-24 13:34:42.219280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68ff99400457'
down_revision: Union[str, Sequence[str], None] = 'f6a6f67f9603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_details', sa.Column('threads', sa.Integer(), nullable=True, comment='Số đầu sợi (Cột B)'))
    op.add_column('bom_details', sa.Column('yarn_dtex', sa.Float(), nullable=True, comment='Độ mảnh sợi dtex (Cột C)'))
    op.add_column('bom_details', sa.Column('yarn_type_name', sa.String(length=100), nullable=True, comment='Mã sợi/Màu (Cột D - VD: 03300-PES-WEISS)'))
    op.add_column('bom_details', sa.Column('twisted', sa.Float(), nullable=True, comment='Hệ số xoắn (Cột E)'))
    op.add_column('bom_details', sa.Column('crossweave_rate', sa.Float(), nullable=True, comment='Độ dôi sợi/Crimp % (Cột F)'))
    op.add_column('bom_details', sa.Column('weight_per_yarn_gm', sa.Float(), nullable=True, comment='Trọng lượng lý thuyết g/m (Cột G)'))
    op.add_column('bom_details', sa.Column('actual_length_cm', sa.Float(), nullable=True, comment='Chiều dài sợi thực tế đo được (Cột H)'))
    op.add_column('bom_details', sa.Column('actual_weight_cal', sa.Float(), nullable=True, comment='Trọng lượng thực tế tính toán (Cột I)'))
    op.add_column('bom_details', sa.Column('weight_percentage', sa.Float(), nullable=True, comment='Tỷ lệ % khối lượng (Cột J)'))
    op.add_column('bom_details', sa.Column('bom_gm', sa.Float(), nullable=True, comment='Định mức chốt cuối cùng (Cột K)'))
    op.drop_column('bom_details', 'quantity_standard')
    op.drop_column('bom_details', 'wastage_rate')
    op.drop_column('bom_details', 'number_of_ends')
    op.drop_column('bom_details', 'quantity_gross')
    op.add_column('bom_headers', sa.Column('width_behind_loom', sa.Float(), nullable=True, comment='Width behind loom (mm/cm)'))
    op.add_column('bom_headers', sa.Column('picks', sa.Integer(), nullable=True, comment='Mật độ sợi ngang (Picks)'))
    op.add_column('bom_headers', sa.Column('target_weight_gm', sa.Float(), nullable=True, comment='Trọng lượng mục tiêu (80.1 g/m)'))
    op.add_column('bom_headers', sa.Column('total_scrap_rate', sa.Float(), nullable=True, comment='Tỷ lệ hao hụt tổng (F18)'))
    op.add_column('bom_headers', sa.Column('total_shrinkage_rate', sa.Float(), nullable=True, comment='Tỷ lệ co rút tổng (F19)'))
    op.drop_column('bom_headers', 'base_quantity')
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.add_column('bom_headers', sa.Column('base_quantity', mysql.FLOAT(), nullable=True))
    op.drop_column('bom_headers', 'total_shrinkage_rate')
    op.drop_column('bom_headers', 'total_scrap_rate')
    op.drop_column('bom_headers', 'target_weight_gm')
    op.drop_column('bom_headers', 'picks')
    op.drop_column('bom_headers', 'width_behind_loom')
    op.add_column('bom_details', sa.Column('quantity_gross', mysql.FLOAT(), nullable=False, comment='Tổng lượng cần xuất kho bao gồm hao hụt'))
    op.add_column('bom_details', sa.Column('number_of_ends', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Tổng số sợi dọc'))
    op.add_column('bom_details', sa.Column('wastage_rate', mysql.FLOAT(), nullable=True, comment='Tỷ lệ hao hụt (%)'))
    op.add_column('bom_details', sa.Column('quantity_standard', mysql.FLOAT(), nullable=False, comment='Số lượng chuẩn (g/m)'))
    op.drop_column('bom_details', 'bom_gm')
    op.drop_column('bom_details', 'weight_percentage')
    op.drop_column('bom_details', 'actual_weight_cal')
    op.drop_column('bom_details', 'actual_length_cm')
    op.drop_column('bom_details', 'weight_per_yarn_gm')
    op.drop_column('bom_details', 'crossweave_rate')
    op.drop_column('bom_details', 'twisted')
    op.drop_column('bom_details', 'yarn_type_name')
    op.drop_column('bom_details', 'yarn_dtex')
    op.drop_column('bom_details', 'threads')
    # ### end Alembic commands ###
