"""add column location for batchs table

Revision ID: 6e8a4b6afbc1
Revises: 0f5a118e182b
Create Date: 2026-01-27 05:54:28.924578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8a4b6afbc1'
down_revision: Union[str, Sequence[str], None] = '0f5a118e182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('location', sa.String(length=10), nullable=True, comment='Vị trí kho/Bin code'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'location')
    # ### end Alembic commands ###
