"""init db schema

Revision ID: 6fa6d9ce2c1a
Revises: 
Create Date: 2025-12-23 02:52:33.568608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa6d9ce2c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('basket_code', sa.String(length=50), nullable=False),
    sa.Column('tare_weight', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('READY', 'IN_USE', 'HOLDING', 'DAMAGED', name='basketstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_index(op.f('ix_baskets_basket_code'), 'baskets', ['basket_code'], unique=True)
    op.create_index(op.f('ix_baskets_basket_id'), 'baskets', ['basket_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_departments_department_name'), 'departments', ['department_name'], unique=True)
    op.create_table('dye_colors',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.Date(), nullable=False),
    sa.Column('hex_code', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('color_id'),
    sa.UniqueConstraint('hex_code')
    )
    op.create_index(op.f('ix_dye_colors_color_id'), 'dye_colors', ['color_id'], unique=False)
    op.create_table('material_issue_slips',
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('issue_slip_id')
    )
    op.create_index(op.f('ix_material_issue_slips_issue_slip_id'), 'material_issue_slips', ['issue_slip_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shifts_shift_id'), 'shifts', ['shift_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    op.create_table('yarn_issue_slips',
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('issue_slip_id')
    )
    op.create_index(op.f('ix_yarn_issue_slips_issue_slip_id'), 'yarn_issue_slips', ['issue_slip_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=False)
    op.create_table('standards',
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('dye_color_id', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.String(length=50), nullable=False),
    sa.Column('thickness_mm', sa.String(length=50), nullable=False),
    sa.Column('breaking_strength_dan', sa.String(length=50), nullable=False),
    sa.Column('elongation_at_load_percent', sa.String(length=50), nullable=False),
    sa.Column('color_fastness_dry', sa.String(length=50), nullable=True),
    sa.Column('color_fastness_wet', sa.String(length=50), nullable=True),
    sa.Column('delta_e', sa.String(length=50), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('weft_density', sa.String(length=50), nullable=False),
    sa.Column('weight_gm', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dye_color_id'], ['dye_colors.color_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('standard_id')
    )
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    op.create_index(op.f('ix_standards_standard_id'), 'standards', ['standard_id'], unique=False)
    op.create_table('yarns',
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('yarn_name', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('yarn_id')
    )
    op.create_index(op.f('ix_yarns_item_code'), 'yarns', ['item_code'], unique=True)
    op.create_index(op.f('ix_yarns_yarn_id'), 'yarns', ['yarn_id'], unique=False)
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=150), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.create_table('semi_finished_export_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('export_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('TO_DYEING', 'DIRECT_SALE', 'OTHER', name='exportreason'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_export_tickets_code'), 'semi_finished_export_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_semi_finished_export_tickets_id'), 'semi_finished_export_tickets', ['id'], unique=False)
    op.create_table('semi_finished_import_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_import_tickets_code'), 'semi_finished_import_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_semi_finished_import_tickets_id'), 'semi_finished_import_tickets', ['id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_work_schedules_work_date'), 'work_schedules', ['work_date'], unique=False)
    op.create_table('yarn_issue_slip_details',
    sa.Column('issue_detail_id', sa.Integer(), nullable=False),
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['issue_slip_id'], ['yarn_issue_slips.issue_slip_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('issue_detail_id')
    )
    op.create_index(op.f('ix_yarn_issue_slip_details_issue_detail_id'), 'yarn_issue_slip_details', ['issue_detail_id'], unique=False)
    op.create_table('yarn_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=True),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('roll_count', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('container_code', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.yarn_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yarn_lots_id'), 'yarn_lots', ['id'], unique=False)
    op.create_index(op.f('ix_yarn_lots_lot_code'), 'yarn_lots', ['lot_code'], unique=True)
    op.create_table('material_issue_slip_details',
    sa.Column('issue_detail_id', sa.Integer(), nullable=False),
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['issue_slip_id'], ['material_issue_slips.issue_slip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('issue_detail_id')
    )
    op.create_index(op.f('ix_material_issue_slip_details_issue_detail_id'), 'material_issue_slip_details', ['issue_detail_id'], unique=False)
    op.create_table('weaving_basket_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_line', sa.String(length=50), nullable=True),
    sa.Column('yarn_load_date', sa.Date(), nullable=False),
    sa.Column('yarn_lot_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('employee_in_id', sa.Integer(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('employee_out_id', sa.Integer(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('net_weight', sa.Float(), nullable=True),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('number_of_knots', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['employee_in_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_out_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.standard_id'], ),
    sa.ForeignKeyConstraint(['yarn_lot_id'], ['yarn_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_basket_tickets_code'), 'weaving_basket_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_weaving_basket_tickets_id'), 'weaving_basket_tickets', ['id'], unique=False)
    op.create_table('semi_finished_export_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_ticket_id', sa.Integer(), nullable=False),
    sa.Column('weaving_ticket_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'EXPORTED', 'PENDING', name='stockstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['export_ticket_id'], ['semi_finished_export_tickets.id'], ),
    sa.ForeignKeyConstraint(['weaving_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_export_details_id'), 'semi_finished_export_details', ['id'], unique=False)
    op.create_table('semi_finished_import_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_ticket_id', sa.Integer(), nullable=False),
    sa.Column('weaving_ticket_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'EXPORTED', 'PENDING', name='stockstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_ticket_id'], ['semi_finished_import_tickets.id'], ),
    sa.ForeignKeyConstraint(['weaving_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_import_details_id'), 'semi_finished_import_details', ['id'], unique=False)
    op.create_table('weaving_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weaving_basket_ticket_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('weft_density', sa.Float(), nullable=True),
    sa.Column('tension_dan', sa.Float(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('weight_gm', sa.Float(), nullable=True),
    sa.Column('bowing', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('inspection_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['weaving_basket_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_inspections_id'), 'weaving_inspections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaving_inspections_id'), table_name='weaving_inspections')
    op.drop_table('weaving_inspections')
    op.drop_index(op.f('ix_semi_finished_import_details_id'), table_name='semi_finished_import_details')
    op.drop_table('semi_finished_import_details')
    op.drop_index(op.f('ix_semi_finished_export_details_id'), table_name='semi_finished_export_details')
    op.drop_table('semi_finished_export_details')
    op.drop_index(op.f('ix_weaving_basket_tickets_id'), table_name='weaving_basket_tickets')
    op.drop_index(op.f('ix_weaving_basket_tickets_code'), table_name='weaving_basket_tickets')
    op.drop_table('weaving_basket_tickets')
    op.drop_index(op.f('ix_material_issue_slip_details_issue_detail_id'), table_name='material_issue_slip_details')
    op.drop_table('material_issue_slip_details')
    op.drop_index(op.f('ix_yarn_lots_lot_code'), table_name='yarn_lots')
    op.drop_index(op.f('ix_yarn_lots_id'), table_name='yarn_lots')
    op.drop_table('yarn_lots')
    op.drop_index(op.f('ix_yarn_issue_slip_details_issue_detail_id'), table_name='yarn_issue_slip_details')
    op.drop_table('yarn_issue_slip_details')
    op.drop_index(op.f('ix_work_schedules_work_date'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_semi_finished_import_tickets_id'), table_name='semi_finished_import_tickets')
    op.drop_index(op.f('ix_semi_finished_import_tickets_code'), table_name='semi_finished_import_tickets')
    op.drop_table('semi_finished_import_tickets')
    op.drop_index(op.f('ix_semi_finished_export_tickets_id'), table_name='semi_finished_export_tickets')
    op.drop_index(op.f('ix_semi_finished_export_tickets_code'), table_name='semi_finished_export_tickets')
    op.drop_table('semi_finished_export_tickets')
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_yarns_yarn_id'), table_name='yarns')
    op.drop_index(op.f('ix_yarns_item_code'), table_name='yarns')
    op.drop_table('yarns')
    op.drop_index(op.f('ix_standards_standard_id'), table_name='standards')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_yarn_issue_slips_issue_slip_id'), table_name='yarn_issue_slips')
    op.drop_table('yarn_issue_slips')
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shifts_shift_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_material_issue_slips_issue_slip_id'), table_name='material_issue_slips')
    op.drop_table('material_issue_slips')
    op.drop_index(op.f('ix_dye_colors_color_id'), table_name='dye_colors')
    op.drop_table('dye_colors')
    op.drop_index(op.f('ix_departments_department_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_baskets_basket_id'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_basket_code'), table_name='baskets')
    op.drop_table('baskets')
    # ### end Alembic commands ###
