"""Add quantity to WeavingTicketYarn final

Revision ID: 847a67d96237
Revises: db924719a1f3
Create Date: 2026-01-30 09:05:10.872890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847a67d96237'
down_revision: Union[str, Sequence[str], None] = 'db924719a1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaving_ticket_yarns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_ticket_yarns_id'), 'weaving_ticket_yarns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaving_ticket_yarns_id'), table_name='weaving_ticket_yarns')
    op.drop_table('weaving_ticket_yarns')
    # ### end Alembic commands ###
