"""Cap nhat lai bang material_export

Revision ID: 8a369577634c
Revises: 684b1028d9f6
Create Date: 2026-03-11 01:35:31.675812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a369577634c'
down_revision: Union[str, Sequence[str], None] = '684b1028d9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_export_details', sa.Column('quantity_kg', sa.Float(), nullable=False, comment='Khối lượng xuất (Kg)'))
    op.add_column('material_export_details', sa.Column('quantity_cones', sa.Integer(), nullable=True, comment='Số cuộn xuất'))
    op.add_column('material_export_details', sa.Column('number_of_pallets', sa.Integer(), nullable=True, comment='Số pallet xuất'))
    op.add_column('material_export_details', sa.Column('loom_id', sa.Integer(), nullable=True, comment='ID của phiên chạy (Loom) nhận hàng'))
    op.drop_constraint(op.f('material_export_details_ibfk_1'), 'material_export_details', type_='foreignkey')
    op.drop_constraint(op.f('material_export_details_ibfk_6'), 'material_export_details', type_='foreignkey')
    op.drop_constraint(op.f('material_export_details_ibfk_4'), 'material_export_details', type_='foreignkey')
    op.drop_constraint(op.f('material_export_details_ibfk_3'), 'material_export_details', type_='foreignkey')
    op.drop_constraint(op.f('material_export_details_ibfk_7'), 'material_export_details', type_='foreignkey')
    op.create_foreign_key(None, 'material_export_details', 'material_exports', ['export_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'material_export_details', 'machine_product_histories', ['loom_id'], ['id'])
    op.drop_column('material_export_details', 'basket_id')
    op.drop_column('material_export_details', 'machine_id')
    op.drop_column('material_export_details', 'machine_line')
    op.drop_column('material_export_details', 'standard_id')
    op.drop_column('material_export_details', 'quantity')
    op.drop_column('material_export_details', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_export_details', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('material_export_details', sa.Column('quantity', mysql.FLOAT(), nullable=False))
    op.add_column('material_export_details', sa.Column('standard_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('material_export_details', sa.Column('machine_line', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('material_export_details', sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('material_export_details', sa.Column('basket_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'material_export_details', type_='foreignkey')
    op.drop_constraint(None, 'material_export_details', type_='foreignkey')
    op.create_foreign_key(op.f('material_export_details_ibfk_7'), 'material_export_details', 'standards', ['standard_id'], ['standard_id'])
    op.create_foreign_key(op.f('material_export_details_ibfk_3'), 'material_export_details', 'material_exports', ['export_id'], ['id'])
    op.create_foreign_key(op.f('material_export_details_ibfk_4'), 'material_export_details', 'machines', ['machine_id'], ['machine_id'])
    op.create_foreign_key(op.f('material_export_details_ibfk_6'), 'material_export_details', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('material_export_details_ibfk_1'), 'material_export_details', 'baskets', ['basket_id'], ['basket_id'])
    op.drop_column('material_export_details', 'loom_id')
    op.drop_column('material_export_details', 'number_of_pallets')
    op.drop_column('material_export_details', 'quantity_cones')
    op.drop_column('material_export_details', 'quantity_kg')
    # ### end Alembic commands ###
