"""create batchs table

Revision ID: 8cf705422537
Revises: 367bcda1e2c5
Create Date: 2026-01-23 02:27:28.269391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf705422537'
down_revision: Union[str, Sequence[str], None] = '367bcda1e2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('internal_batch_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_batch_no', sa.String(length=100), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('receipt_detail_id', sa.Integer(), nullable=True),
    sa.Column('qc_status', sa.Enum('PENDING', 'PASS', 'FAIL', 'EXPIRED', name='batchqcstatus'), nullable=True),
    sa.Column('qc_note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receipt_detail_id'], ['material_receipt_details.detail_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batches_internal_batch_code'), 'batches', ['internal_batch_code'], unique=True)
    op.create_index(op.f('ix_batches_supplier_batch_no'), 'batches', ['supplier_batch_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_supplier_batch_no'), table_name='batches')
    op.drop_index(op.f('ix_batches_internal_batch_code'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
