"""create import_declaration and import_declaration_detail table

Revision ID: 91bae4191a6a
Revises: 9cfbf9ce3185
Create Date: 2026-01-21 07:54:02.256532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bae4191a6a'
down_revision: Union[str, Sequence[str], None] = '9cfbf9ce3185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_no', sa.String(length=50), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('type_of_import', sa.Enum('E31', 'E21', 'A11', 'A12', 'G11', name='importtype'), nullable=False),
    sa.Column('bill_of_lading', sa.String(length=50), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('total_tax_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_declarations_declaration_no'), 'import_declarations', ['declaration_no'], unique=True)
    op.create_index(op.f('ix_import_declarations_id'), 'import_declarations', ['id'], unique=False)
    op.create_table('import_declaration_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('po_detail_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('hs_code_actual', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_details.detail_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_import_declaration_details_detail_id'), 'import_declaration_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_declaration_details_detail_id'), table_name='import_declaration_details')
    op.drop_table('import_declaration_details')
    op.drop_index(op.f('ix_import_declarations_id'), table_name='import_declarations')
    op.drop_index(op.f('ix_import_declarations_declaration_no'), table_name='import_declarations')
    op.drop_table('import_declarations')
    # ### end Alembic commands ###
