"""Cap nhat lai bang standars

Revision ID: 936cc04dfea3
Revises: 8a369577634c
Create Date: 2026-03-11 05:38:24.044585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '936cc04dfea3'
down_revision: Union[str, Sequence[str], None] = '8a369577634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('curved', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('standards_ibfk_1'), 'standards', type_='foreignkey')
    op.drop_column('standards', 'appearance')
    op.drop_column('standards', 'dye_color_id')
    op.drop_column('standards', 'color_fastness_wet')
    op.drop_column('standards', 'color_fastness_dry')
    op.drop_column('standards', 'delta_e')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('delta_e', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('standards', sa.Column('color_fastness_dry', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('standards', sa.Column('color_fastness_wet', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('standards', sa.Column('dye_color_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standards', sa.Column('appearance', mysql.TEXT(), nullable=True))
    op.create_foreign_key(op.f('standards_ibfk_1'), 'standards', 'dye_colors', ['dye_color_id'], ['color_id'])
    op.drop_column('standards', 'curved')
    # ### end Alembic commands ###
