"""create purchase headers  and purchase details table

Revision ID: 9cfbf9ce3185
Revises: 1534c2487c44
Create Date: 2026-01-21 03:21:48.603440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfbf9ce3185'
down_revision: Union[str, Sequence[str], None] = '1534c2487c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('incoterm', sa.Enum('EXW', 'FOB', 'CIF', 'DDP', 'DAP', name='incotermtype'), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CONFIRMED', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='postatus'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('purchase_order_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('received_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_purchase_order_details_detail_id'), 'purchase_order_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_details_detail_id'), table_name='purchase_order_details')
    op.drop_table('purchase_order_details')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
