"""update color_name of dye_colors

Revision ID: 9e102f5d43b7
Revises: 6fa6d9ce2c1a
Create Date: 2025-12-23 03:53:01.627674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e102f5d43b7'
down_revision: Union[str, Sequence[str], None] = '6fa6d9ce2c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dye_colors', 'color_name',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dye_colors', 'color_name',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
