"""them cot kg_per_bobbin cho materials

Revision ID: a2667b7a7f18
Revises: 673cfc20dda7
Create Date: 2026-02-23 06:27:29.912075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2667b7a7f18'
down_revision: Union[str, Sequence[str], None] = '673cfc20dda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('kg_per_bobbin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'kg_per_bobbin')
    # ### end Alembic commands ###
