"""Them unique cho standar

Revision ID: a2ebfb7cfa57
Revises: e268de821dba
Create Date: 2026-02-10 07:39:27.550353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ebfb7cfa57'
down_revision: Union[str, Sequence[str], None] = 'e268de821dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'standards', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standards', type_='unique')
    # ### end Alembic commands ###
