"""create batchs table vs2

Revision ID: a8b88f0c409f
Revises: 8cf705422537
Create Date: 2026-01-23 04:25:22.482139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b88f0c409f'
down_revision: Union[str, Sequence[str], None] = '8cf705422537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_receipt_details', sa.Column('origin_country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_receipt_details', 'origin_country')
    # ### end Alembic commands ###
