"""Them bang product_types va cap nhat bang product

Revision ID: b3cae7bbd9b0
Revises: 1bbbfa850fe0
Create Date: 2026-02-28 03:31:46.396080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cae7bbd9b0'
down_revision: Union[str, Sequence[str], None] = '1bbbfa850fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_type_id')
    )
    op.create_index(op.f('ix_product_types_product_type_id'), 'product_types', ['product_type_id'], unique=False)
    op.add_column('products', sa.Column('product_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_types', ['product_type_id'], ['product_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_type_id')
    op.drop_index(op.f('ix_product_types_product_type_id'), table_name='product_types')
    op.drop_table('product_types')
    # ### end Alembic commands ###
