"""init_all_tables

Revision ID: b4501a8ba179
Revises: 
Create Date: 2025-12-21 16:01:05.913430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4501a8ba179'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_departments_department_name'), 'departments', ['department_name'], unique=True)
    op.create_table('material_issue_slips',
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('issue_slip_id')
    )
    op.create_index(op.f('ix_material_issue_slips_issue_slip_id'), 'material_issue_slips', ['issue_slip_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shifts_shift_id'), 'shifts', ['shift_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    op.create_table('yarn_issue_slips',
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('issue_slip_id')
    )
    op.create_index(op.f('ix_yarn_issue_slips_issue_slip_id'), 'yarn_issue_slips', ['issue_slip_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=False)
    op.create_table('yarns',
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('yarn_name', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('yarn_id')
    )
    op.create_index(op.f('ix_yarns_item_code'), 'yarns', ['item_code'], unique=True)
    op.create_index(op.f('ix_yarns_yarn_id'), 'yarns', ['yarn_id'], unique=False)
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=150), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.create_table('yarn_issue_slip_details',
    sa.Column('issue_detail_id', sa.Integer(), nullable=False),
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['issue_slip_id'], ['yarn_issue_slips.issue_slip_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('issue_detail_id')
    )
    op.create_index(op.f('ix_yarn_issue_slip_details_issue_detail_id'), 'yarn_issue_slip_details', ['issue_detail_id'], unique=False)
    op.create_table('yarn_lots',
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('roll_count', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('container_code', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.yarn_id'], ),
    sa.PrimaryKeyConstraint('lot_code', 'yarn_id')
    )
    op.create_index(op.f('ix_yarn_lots_lot_code'), 'yarn_lots', ['lot_code'], unique=False)
    op.create_table('material_issue_slip_details',
    sa.Column('issue_detail_id', sa.Integer(), nullable=False),
    sa.Column('issue_slip_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['issue_slip_id'], ['material_issue_slips.issue_slip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('issue_detail_id')
    )
    op.create_index(op.f('ix_material_issue_slip_details_issue_detail_id'), 'material_issue_slip_details', ['issue_detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_issue_slip_details_issue_detail_id'), table_name='material_issue_slip_details')
    op.drop_table('material_issue_slip_details')
    op.drop_index(op.f('ix_yarn_lots_lot_code'), table_name='yarn_lots')
    op.drop_table('yarn_lots')
    op.drop_index(op.f('ix_yarn_issue_slip_details_issue_detail_id'), table_name='yarn_issue_slip_details')
    op.drop_table('yarn_issue_slip_details')
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_yarns_yarn_id'), table_name='yarns')
    op.drop_index(op.f('ix_yarns_item_code'), table_name='yarns')
    op.drop_table('yarns')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_yarn_issue_slips_issue_slip_id'), table_name='yarn_issue_slips')
    op.drop_table('yarn_issue_slips')
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shifts_shift_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_material_issue_slips_issue_slip_id'), table_name='material_issue_slips')
    op.drop_table('material_issue_slips')
    op.drop_index(op.f('ix_departments_department_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
