"""update bom table 

Revision ID: b789be87d93d
Revises: 0f9f4b4b476f
Create Date: 2026-01-26 04:20:18.753395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b789be87d93d'
down_revision: Union[str, Sequence[str], None] = '0f9f4b4b476f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_headers', sa.Column('applicable_year', sa.Integer(), nullable=False, comment='Năm áp dụng (VD: 2026)'))
    op.alter_column('bom_headers', 'version',
               existing_type=mysql.INTEGER(),
               comment='Phiên bản sửa đổi trong năm',
               existing_nullable=True)
    op.drop_index(op.f('ix_bom_headers_bom_code'), table_name='bom_headers')
    op.create_unique_constraint('uq_bom_product_year', 'bom_headers', ['product_id', 'applicable_year'])
    op.drop_column('bom_headers', 'bom_name')
    op.drop_column('bom_headers', 'bom_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_headers', sa.Column('bom_code', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('bom_headers', sa.Column('bom_name', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint('uq_bom_product_year', 'bom_headers', type_='unique')
    op.create_index(op.f('ix_bom_headers_bom_code'), 'bom_headers', ['bom_code'], unique=True)
    op.alter_column('bom_headers', 'version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Phiên bản sửa đổi trong năm',
               existing_nullable=True)
    op.drop_column('bom_headers', 'applicable_year')
    # ### end Alembic commands ###
