"""them cot so seri và speed cho machine

Revision ID: b874abdaa18d
Revises: a2667b7a7f18
Create Date: 2026-02-23 09:12:19.093335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b874abdaa18d'
down_revision: Union[str, Sequence[str], None] = 'a2667b7a7f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('speed', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'machines', ['machine_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machines', type_='unique')
    op.drop_column('machines', 'speed')
    op.drop_column('machines', 'serial_number')
    # ### end Alembic commands ###
