"""update images column for products

Revision ID: bb645ccedc2d
Revises: 1c5ecb0c0859
Create Date: 2026-01-06 01:33:07.611644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb645ccedc2d'
down_revision: Union[str, Sequence[str], None] = '1c5ecb0c0859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'departments', ['department_id'], ['department_id'])
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
