"""add payment_term column for suppliers table vs2 

Revision ID: befbc3b67da8
Revises: 3220018f8dd6
Create Date: 2026-01-19 03:30:39.357543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'befbc3b67da8'
down_revision: Union[str, Sequence[str], None] = '3220018f8dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_column('suppliers', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('country_code', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('suppliers', 'country')
    # ### end Alembic commands ###
