"""Cho phep email nhan vien la null

Revision ID: c5d0dd78bf4c
Revises: b874abdaa18d
Create Date: 2026-02-24 02:04:57.652260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d0dd78bf4c'
down_revision: Union[str, Sequence[str], None] = 'b874abdaa18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
