"""Khoi tao CSDL

Revision ID: d0aa037a7e4f
Revises: 
Create Date: 2026-02-01 14:23:51.618622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0aa037a7e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('basket_code', sa.String(length=50), nullable=False),
    sa.Column('tare_weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'IN_USE', 'HOLDING', 'DAMAGED', name='basketstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_index(op.f('ix_baskets_basket_code'), 'baskets', ['basket_code'], unique=True)
    op.create_index(op.f('ix_baskets_basket_id'), 'baskets', ['basket_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_departments_department_name'), 'departments', ['department_name'], unique=True)
    op.create_table('dye_colors',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=50), nullable=False),
    sa.Column('hex_code', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('color_id'),
    sa.UniqueConstraint('hex_code')
    )
    op.create_index(op.f('ix_dye_colors_color_id'), 'dye_colors', ['color_id'], unique=False)
    op.create_table('import_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_no', sa.String(length=50), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('type_of_import', sa.Enum('E31', 'E21', 'A11', 'A12', 'G11', name='importtype'), nullable=False),
    sa.Column('bill_of_lading', sa.String(length=50), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('total_tax_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_declarations_declaration_no'), 'import_declarations', ['declaration_no'], unique=True)
    op.create_index(op.f('ix_import_declarations_id'), 'import_declarations', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('STOPPED', 'RUNNING', 'MAINTENANCE', 'SPINNING', name='machinestatus'), nullable=False),
    sa.Column('area', sa.Enum('SECTION_A', 'SECTION_B', 'SECTION_C', name='machinearea'), nullable=True),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_index(op.f('ix_machines_area'), 'machines', ['area'], unique=False)
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shifts_shift_id'), 'shifts', ['shift_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('origin_type', sa.Enum('DOMESTIC', 'IMPORT', name='supplierorigintype'), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency_default', sa.Enum('VND', 'USD', 'CNY', 'EUR', name='currencytype'), nullable=True),
    sa.Column('payment_term', sa.Enum('TT', 'LC', 'NET_30', 'NET_45', 'NET_60', 'COD', 'IMMEDIATE', name='paymenttermtype'), nullable=True, comment='Điều khoản thanh toán mặc định (T/T, L/C, Net 30...)'),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True, comment='Thời gian giao hàng trung bình (ngày)'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_name'), 'warehouses', ['warehouse_name'], unique=True)
    op.create_table('bom_headers',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('applicable_year', sa.Integer(), nullable=False, comment='Năm áp dụng (VD: 2026)'),
    sa.Column('width_behind_loom', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Width behind loom (mm/cm)'),
    sa.Column('picks', sa.Integer(), nullable=True, comment='Mật độ sợi ngang (Picks)'),
    sa.Column('target_weight_gm', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Trọng lượng mục tiêu (80.1 g/m)'),
    sa.Column('total_scrap_rate', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Tỷ lệ hao hụt tổng (F18)'),
    sa.Column('total_shrinkage_rate', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Tỷ lệ co rút tổng (F19)'),
    sa.Column('version', sa.Integer(), nullable=True, comment='Phiên bản sửa đổi trong năm'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('bom_id'),
    sa.UniqueConstraint('product_id', 'applicable_year', name='uq_bom_product_year')
    )
    op.create_index(op.f('ix_bom_headers_bom_id'), 'bom_headers', ['bom_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('machine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_logs_id'), 'machine_logs', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('spec_denier', sa.String(length=50), nullable=True),
    sa.Column('spec_filament', sa.Integer(), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True),
    sa.Column('uom_base_id', sa.Integer(), nullable=False),
    sa.Column('uom_production_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uom_base_id'], ['units.unit_id'], ),
    sa.ForeignKeyConstraint(['uom_production_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('incoterm', sa.Enum('EXW', 'FOB', 'CIF', 'DDP', 'DAP', name='incotermtype'), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CONFIRMED', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='postatus'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('standards',
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('dye_color_id', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.String(length=50), nullable=False),
    sa.Column('thickness_mm', sa.String(length=50), nullable=False),
    sa.Column('breaking_strength_dan', sa.String(length=50), nullable=False),
    sa.Column('elongation_at_load_percent', sa.String(length=50), nullable=False),
    sa.Column('color_fastness_dry', sa.String(length=50), nullable=True),
    sa.Column('color_fastness_wet', sa.String(length=50), nullable=True),
    sa.Column('delta_e', sa.String(length=50), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('weft_density', sa.String(length=50), nullable=False),
    sa.Column('weight_gm', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dye_color_id'], ['dye_colors.color_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('standard_id')
    )
    op.create_index(op.f('ix_standards_standard_id'), 'standards', ['standard_id'], unique=False)
    op.create_table('weaving_daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_meters', sa.Float(), nullable=True),
    sa.Column('total_kg', sa.Float(), nullable=True),
    sa.Column('active_machine_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'product_id', name='uix_date_product')
    )
    op.create_index(op.f('ix_weaving_daily_productions_date'), 'weaving_daily_productions', ['date'], unique=False)
    op.create_index(op.f('ix_weaving_daily_productions_id'), 'weaving_daily_productions', ['id'], unique=False)
    op.create_table('bom_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('GROUND', 'GRD. MARKER', 'EDGE', 'BINDER', 'STUFFER', 'STUFFER MAKER', 'LOCK', 'CATCH CORD', 'FILLING', '2ND FILLING', name='bomcomponenttype'), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=True, comment='Số đầu sợi (Cột B)'),
    sa.Column('yarn_dtex', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Độ mảnh sợi dtex (Cột C)'),
    sa.Column('yarn_type_name', sa.String(length=100), nullable=True, comment='Mã sợi/Màu (Cột D)'),
    sa.Column('twisted', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Hệ số xoắn (Cột E)'),
    sa.Column('crossweave_rate', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Độ dôi sợi/Crimp % (Cột F)'),
    sa.Column('weight_per_yarn_gm', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Trọng lượng lý thuyết g/m (Cột G)'),
    sa.Column('actual_length_cm', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Chiều dài sợi thực tế đo được (Cột H)'),
    sa.Column('actual_weight_cal', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Trọng lượng thực tế tính toán (Cột I)'),
    sa.Column('weight_percentage', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Tỷ lệ % khối lượng (Cột J)'),
    sa.Column('bom_gm', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Định mức chốt cuối cùng (Cột K)'),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_headers.bom_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_bom_details_detail_id'), 'bom_details', ['detail_id'], unique=False)
    op.create_table('material_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_code', sa.String(length=50), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('exporter_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['exporter_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_exports_export_code'), 'material_exports', ['export_code'], unique=True)
    op.create_index(op.f('ix_material_exports_id'), 'material_exports', ['id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('po_header_id', sa.Integer(), nullable=True),
    sa.Column('declaration_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('container_no', sa.String(length=50), nullable=True, comment='Số Container'),
    sa.Column('seal_no', sa.String(length=50), nullable=True, comment='Số Seal (Chì)'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['po_header_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_index(op.f('ix_material_receipts_receipt_id'), 'material_receipts', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_receipt_number'), 'material_receipts', ['receipt_number'], unique=True)
    op.create_table('purchase_order_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('received_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_purchase_order_details_detail_id'), 'purchase_order_details', ['detail_id'], unique=False)
    op.create_table('semi_finished_export_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('export_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('TO_DYEING', 'DIRECT_SALE', 'OTHER', name='exportreason'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_export_tickets_code'), 'semi_finished_export_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_semi_finished_export_tickets_id'), 'semi_finished_export_tickets', ['id'], unique=False)
    op.create_table('semi_finished_import_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_import_tickets_code'), 'semi_finished_import_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_semi_finished_import_tickets_id'), 'semi_finished_import_tickets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('weaving_basket_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_line', sa.Integer(), nullable=False),
    sa.Column('yarn_load_date', sa.Date(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('employee_in_id', sa.Integer(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('employee_out_id', sa.Integer(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('net_weight', sa.Float(), nullable=True),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('number_of_knots', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['employee_in_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_out_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.standard_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_basket_tickets_code'), 'weaving_basket_tickets', ['code'], unique=True)
    op.create_index(op.f('ix_weaving_basket_tickets_id'), 'weaving_basket_tickets', ['id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_work_schedules_work_date'), 'work_schedules', ['work_date'], unique=False)
    op.create_table('import_declaration_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('po_detail_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('hs_code_actual', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_details.detail_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_import_declaration_details_detail_id'), 'import_declaration_details', ['detail_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_action'), 'logs', ['action'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_target_type'), 'logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_table('material_receipt_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('po_quantity_kg', sa.Float(), nullable=True, comment='SL Kg trên chứng từ'),
    sa.Column('po_quantity_cones', sa.Integer(), nullable=True, comment='SL Cuộn trên chứng từ'),
    sa.Column('received_quantity_kg', sa.Float(), nullable=False, comment='SL Kg thực nhập'),
    sa.Column('received_quantity_cones', sa.Integer(), nullable=True, comment='SL Cuộn thực nhập'),
    sa.Column('number_of_pallets', sa.Integer(), nullable=True, comment='Tổng số Pallet/Kiện hàng'),
    sa.Column('supplier_batch_no', sa.String(length=100), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True, comment='Vị trí kho chi tiết (Bin Code)'),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['material_receipts.receipt_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_material_receipt_details_detail_id'), 'material_receipt_details', ['detail_id'], unique=False)
    op.create_table('semi_finished_export_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_ticket_id', sa.Integer(), nullable=False),
    sa.Column('weaving_ticket_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'EXPORTED', 'PENDING', name='stockstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['export_ticket_id'], ['semi_finished_export_tickets.id'], ),
    sa.ForeignKeyConstraint(['weaving_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_export_details_id'), 'semi_finished_export_details', ['id'], unique=False)
    op.create_table('semi_finished_import_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_ticket_id', sa.Integer(), nullable=False),
    sa.Column('weaving_ticket_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'EXPORTED', 'PENDING', name='stockstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_ticket_id'], ['semi_finished_import_tickets.id'], ),
    sa.ForeignKeyConstraint(['weaving_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_import_details_id'), 'semi_finished_import_details', ['id'], unique=False)
    op.create_table('weaving_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weaving_basket_ticket_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('weft_density', sa.Float(), nullable=True),
    sa.Column('tension_dan', sa.Float(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('weight_gm', sa.Float(), nullable=True),
    sa.Column('bowing', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('inspection_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['weaving_basket_ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_inspections_id'), 'weaving_inspections', ['id'], unique=False)
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('internal_batch_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_batch_no', sa.String(length=100), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True, comment='Vị trí kho/Bin code'),
    sa.Column('receipt_detail_id', sa.Integer(), nullable=True),
    sa.Column('qc_status', sa.Enum('PENDING', 'PASS', 'FAIL', 'EXPIRED', name='batchqcstatus'), nullable=True),
    sa.Column('qc_note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receipt_detail_id'], ['material_receipt_details.detail_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batches_internal_batch_code'), 'batches', ['internal_batch_code'], unique=True)
    op.create_index(op.f('ix_batches_supplier_batch_no'), 'batches', ['supplier_batch_no'], unique=False)
    op.create_table('inventory_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_reserved', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'warehouse_id', 'batch_id', name='uix_stock_loc_batch')
    )
    op.create_index(op.f('ix_inventory_stocks_id'), 'inventory_stocks', ['id'], unique=False)
    op.create_table('iqc_results',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('tester_name', sa.String(length=100), nullable=True),
    sa.Column('tensile_strength', sa.Float(), nullable=True),
    sa.Column('elongation', sa.Float(), nullable=True),
    sa.Column('color_fastness', sa.Float(), nullable=True),
    sa.Column('final_result', sa.Enum('PASS', 'FAIL', 'PENDING', name='iqcresultstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_iqc_results_test_id'), 'iqc_results', ['test_id'], unique=False)
    op.create_table('material_export_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('export_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('machine_line', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['export_id'], ['material_exports.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.standard_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_material_export_details_detail_id'), 'material_export_details', ['detail_id'], unique=False)
    op.create_table('weaving_ticket_yarns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_ticket_yarns_id'), 'weaving_ticket_yarns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaving_ticket_yarns_id'), table_name='weaving_ticket_yarns')
    op.drop_table('weaving_ticket_yarns')
    op.drop_index(op.f('ix_material_export_details_detail_id'), table_name='material_export_details')
    op.drop_table('material_export_details')
    op.drop_index(op.f('ix_iqc_results_test_id'), table_name='iqc_results')
    op.drop_table('iqc_results')
    op.drop_index(op.f('ix_inventory_stocks_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    op.drop_index(op.f('ix_batches_supplier_batch_no'), table_name='batches')
    op.drop_index(op.f('ix_batches_internal_batch_code'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_weaving_inspections_id'), table_name='weaving_inspections')
    op.drop_table('weaving_inspections')
    op.drop_index(op.f('ix_semi_finished_import_details_id'), table_name='semi_finished_import_details')
    op.drop_table('semi_finished_import_details')
    op.drop_index(op.f('ix_semi_finished_export_details_id'), table_name='semi_finished_export_details')
    op.drop_table('semi_finished_export_details')
    op.drop_index(op.f('ix_material_receipt_details_detail_id'), table_name='material_receipt_details')
    op.drop_table('material_receipt_details')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_target_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_action'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_import_declaration_details_detail_id'), table_name='import_declaration_details')
    op.drop_table('import_declaration_details')
    op.drop_index(op.f('ix_work_schedules_work_date'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_weaving_basket_tickets_id'), table_name='weaving_basket_tickets')
    op.drop_index(op.f('ix_weaving_basket_tickets_code'), table_name='weaving_basket_tickets')
    op.drop_table('weaving_basket_tickets')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_semi_finished_import_tickets_id'), table_name='semi_finished_import_tickets')
    op.drop_index(op.f('ix_semi_finished_import_tickets_code'), table_name='semi_finished_import_tickets')
    op.drop_table('semi_finished_import_tickets')
    op.drop_index(op.f('ix_semi_finished_export_tickets_id'), table_name='semi_finished_export_tickets')
    op.drop_index(op.f('ix_semi_finished_export_tickets_code'), table_name='semi_finished_export_tickets')
    op.drop_table('semi_finished_export_tickets')
    op.drop_index(op.f('ix_purchase_order_details_detail_id'), table_name='purchase_order_details')
    op.drop_table('purchase_order_details')
    op.drop_index(op.f('ix_material_receipts_receipt_number'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_receipt_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_material_exports_id'), table_name='material_exports')
    op.drop_index(op.f('ix_material_exports_export_code'), table_name='material_exports')
    op.drop_table('material_exports')
    op.drop_index(op.f('ix_bom_details_detail_id'), table_name='bom_details')
    op.drop_table('bom_details')
    op.drop_index(op.f('ix_weaving_daily_productions_id'), table_name='weaving_daily_productions')
    op.drop_index(op.f('ix_weaving_daily_productions_date'), table_name='weaving_daily_productions')
    op.drop_table('weaving_daily_productions')
    op.drop_index(op.f('ix_standards_standard_id'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_machine_logs_id'), table_name='machine_logs')
    op.drop_table('machine_logs')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_bom_headers_bom_id'), table_name='bom_headers')
    op.drop_table('bom_headers')
    op.drop_index(op.f('ix_warehouses_warehouse_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shifts_shift_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_area'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_import_declarations_id'), table_name='import_declarations')
    op.drop_index(op.f('ix_import_declarations_declaration_no'), table_name='import_declarations')
    op.drop_table('import_declarations')
    op.drop_index(op.f('ix_dye_colors_color_id'), table_name='dye_colors')
    op.drop_table('dye_colors')
    op.drop_index(op.f('ix_departments_department_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_baskets_basket_id'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_basket_code'), table_name='baskets')
    op.drop_table('baskets')
    # ### end Alembic commands ###
