"""Thêm WeavingTicketYarn

Revision ID: db924719a1f3
Revises: e373e4b6fe8a
Create Date: 2026-01-30 03:30:23.488184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db924719a1f3'
down_revision: Union[str, Sequence[str], None] = 'e373e4b6fe8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaving_ticket_yarns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['weaving_basket_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaving_ticket_yarns_id'), 'weaving_ticket_yarns', ['id'], unique=False)
    op.add_column('material_export_details', sa.Column('component_type', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('weaving_basket_tickets_ibfk_7'), 'weaving_basket_tickets', type_='foreignkey')
    op.drop_column('weaving_basket_tickets', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaving_basket_tickets', sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('weaving_basket_tickets_ibfk_7'), 'weaving_basket_tickets', 'batches', ['batch_id'], ['batch_id'])
    op.drop_column('material_export_details', 'component_type')
    op.drop_index(op.f('ix_weaving_ticket_yarns_id'), table_name='weaving_ticket_yarns')
    op.drop_table('weaving_ticket_yarns')
    # ### end Alembic commands ###
