"""Thêm trường người xuất phiếu nguyên vật liệu và chỉnh sửa cho phép null ở phiếu rổ dệt

Revision ID: e373e4b6fe8a
Revises: 8bc89f7a56b7
Create Date: 2026-01-29 07:21:43.405116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e373e4b6fe8a'
down_revision: Union[str, Sequence[str], None] = '8bc89f7a56b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_exports', sa.Column('exporter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_exports', 'employees', ['exporter_id'], ['employee_id'])
    op.alter_column('weaving_basket_tickets', 'standard_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('weaving_basket_tickets', 'machine_line',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('weaving_basket_tickets', 'basket_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('weaving_basket_tickets', 'employee_in_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weaving_basket_tickets', 'employee_in_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('weaving_basket_tickets', 'basket_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('weaving_basket_tickets', 'machine_line',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('weaving_basket_tickets', 'standard_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'material_exports', type_='foreignkey')
    op.drop_column('material_exports', 'exporter_id')
    # ### end Alembic commands ###
