"""Them bang Incoterm, po_status, po_header, po_details

Revision ID: eae49273b8c0
Revises: 3f3456c7086b
Create Date: 2026-03-06 05:33:16.613090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eae49273b8c0'
down_revision: Union[str, Sequence[str], None] = '3f3456c7086b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoterms',
    sa.Column('incoterm_id', sa.Integer(), nullable=False),
    sa.Column('incoterm_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('incoterm_id')
    )
    op.create_index(op.f('ix_incoterms_incoterm_code'), 'incoterms', ['incoterm_code'], unique=True)
    op.create_index(op.f('ix_incoterms_incoterm_id'), 'incoterms', ['incoterm_id'], unique=False)
    op.create_table('po_statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_po_statuses_status_code'), 'po_statuses', ['status_code'], unique=True)
    op.create_index(op.f('ix_po_statuses_status_id'), 'po_statuses', ['status_id'], unique=False)
    op.add_column('purchase_order_details', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('purchase_order_details', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('purchase_order_details', sa.Column('quantity_kg', sa.Float(), nullable=False))
    op.drop_constraint(op.f('purchase_order_details_ibfk_3'), 'purchase_order_details', type_='foreignkey')
    op.drop_column('purchase_order_details', 'uom_id')
    op.drop_column('purchase_order_details', 'quantity')
    op.add_column('purchase_orders', sa.Column('incoterm_id', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'incoterms', ['incoterm_id'], ['incoterm_id'])
    op.create_foreign_key(None, 'purchase_orders', 'po_statuses', ['status_id'], ['status_id'])
    op.drop_column('purchase_orders', 'currency')
    op.drop_column('purchase_orders', 'incoterm')
    op.drop_column('purchase_orders', 'status')
    op.drop_column('purchase_orders', 'exchange_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('exchange_rate', mysql.FLOAT(), nullable=True))
    op.add_column('purchase_orders', sa.Column('status', mysql.ENUM('DRAFT', 'SENT', 'CONFIRMED', 'PARTIAL', 'COMPLETED', 'CANCELLED'), nullable=True))
    op.add_column('purchase_orders', sa.Column('incoterm', mysql.ENUM('EXW', 'FOB', 'CIF', 'DDP', 'DAP'), nullable=True))
    op.add_column('purchase_orders', sa.Column('currency', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'status_id')
    op.drop_column('purchase_orders', 'incoterm_id')
    op.add_column('purchase_order_details', sa.Column('quantity', mysql.FLOAT(), nullable=False))
    op.add_column('purchase_order_details', sa.Column('uom_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('purchase_order_details_ibfk_3'), 'purchase_order_details', 'units', ['uom_id'], ['unit_id'])
    op.drop_column('purchase_order_details', 'quantity_kg')
    op.drop_column('purchase_order_details', 'exchange_rate')
    op.drop_column('purchase_order_details', 'currency')
    op.drop_index(op.f('ix_po_statuses_status_id'), table_name='po_statuses')
    op.drop_index(op.f('ix_po_statuses_status_code'), table_name='po_statuses')
    op.drop_table('po_statuses')
    op.drop_index(op.f('ix_incoterms_incoterm_id'), table_name='incoterms')
    op.drop_index(op.f('ix_incoterms_incoterm_code'), table_name='incoterms')
    op.drop_table('incoterms')
    # ### end Alembic commands ###
