"""remove supplierId for baskets and machines table, update suppliers table

Revision ID: ef5a4566edd4
Revises: f702f6c0d199
Create Date: 2026-01-12 07:18:42.537441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef5a4566edd4'
down_revision: Union[str, Sequence[str], None] = 'f702f6c0d199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baskets', 'supplier')
    op.drop_constraint(op.f('machines_ibfk_1'), 'machines', type_='foreignkey')
    op.drop_column('machines', 'supplier_id')
    op.add_column('suppliers', sa.Column('short_name', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('origin_type', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('country_code', sa.String(length=3), nullable=True))
    op.add_column('suppliers', sa.Column('currency_default', sa.String(length=3), nullable=True))
    op.add_column('suppliers', sa.Column('contact_person', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('tax_code', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('suppliers', 'supplier_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('suppliers', 'phone')
    op.drop_column('suppliers', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('note', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('suppliers', sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
    op.alter_column('suppliers', 'address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'supplier_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('suppliers', 'is_active')
    op.drop_column('suppliers', 'lead_time_days')
    op.drop_column('suppliers', 'tax_code')
    op.drop_column('suppliers', 'contact_person')
    op.drop_column('suppliers', 'currency_default')
    op.drop_column('suppliers', 'country_code')
    op.drop_column('suppliers', 'origin_type')
    op.drop_column('suppliers', 'short_name')
    op.add_column('machines', sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('machines_ibfk_1'), 'machines', 'suppliers', ['supplier_id'], ['supplier_id'])
    op.add_column('baskets', sa.Column('supplier', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
