"""Cap nhat cho phep null bang purchase_orders 

Revision ID: efcd146d2751
Revises: eae49273b8c0
Create Date: 2026-03-06 09:25:24.540915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcd146d2751'
down_revision: Union[str, Sequence[str], None] = 'eae49273b8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
