"""create table material_export and material_export_detail table vs3

Revision ID: f42d70829bf9
Revises: 4457710f96c5
Create Date: 2026-01-28 09:23:10.193732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f42d70829bf9'
down_revision: Union[str, Sequence[str], None] = '4457710f96c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaving_basket_tickets', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('weaving_basket_tickets_ibfk_7'), 'weaving_basket_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'weaving_basket_tickets', 'batches', ['batch_id'], ['batch_id'])
    op.drop_column('weaving_basket_tickets', 'yarn_lot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaving_basket_tickets', sa.Column('yarn_lot_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weaving_basket_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('weaving_basket_tickets_ibfk_7'), 'weaving_basket_tickets', 'yarn_lots', ['yarn_lot_id'], ['id'])
    op.drop_column('weaving_basket_tickets', 'batch_id')
    # ### end Alembic commands ###
