"""create table inventorys table

Revision ID: f577c0034c83
Revises: 68d207d139a9
Create Date: 2026-01-28 02:48:45.967936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f577c0034c83'
down_revision: Union[str, Sequence[str], None] = '68d207d139a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_reserved', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'warehouse_id', 'batch_id', name='uix_stock_loc_batch')
    )
    op.create_index(op.f('ix_inventory_stocks_id'), 'inventory_stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_stocks_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    # ### end Alembic commands ###
