"""Them cot cờ để tính tiền trên PO

Revision ID: f6ac2f576aa8
Revises: 28f1b0ecc033
Create Date: 2026-02-02 04:08:15.412894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ac2f576aa8'
down_revision: Union[str, Sequence[str], None] = '28f1b0ecc033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_details', sa.Column('is_pricing_by_roll', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_details', 'is_pricing_by_roll')
    # ### end Alembic commands ###
