"""update employeeId for user table

Revision ID: f702f6c0d199
Revises: 9a7f731fa7a9
Create Date: 2026-01-12 01:38:57.858118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f702f6c0d199'
down_revision: Union[str, Sequence[str], None] = '9a7f731fa7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # [FIX] Comment dòng này lại vì cột employee_id đã tồn tại
    # op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=True))
    
    # Giữ lại dòng này để tạo liên kết khóa ngoại (nếu chưa có)
    # Lưu ý: Nếu chạy tiếp mà báo lỗi "Duplicate foreign key..." thì bạn comment nốt dòng này lại nhé.
    try:
        op.create_foreign_key('fk_users_employees', 'users', 'employees', ['employee_id'], ['employee_id'])
    except Exception:
        pass # Bỏ qua lỗi nếu khóa ngoại đã tồn tại
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_employees', 'users', type_='foreignkey')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###